# Lab 5: Project Roadmap

In this assignment, you will advance your course project by creating a roadmap of tasks and performing a critical exploratory analysis of your dataset.

In [2]:
# --- Import Libraries ---
# additional libraries need to be added to the requirements.txt file (see README.md for more details)
import pandas as pd
import numpy as np

## Part 1: Data Ingestion & Reality Check (1.5 Points)

Your first task is to load the data and verify that it matches your mental model of the dataset.

In [3]:
# TODO: Load your dataset
df = pd.read_csv('../data/amazon.csv')

In [ ]:
# TODO: Print the shape (rows, columns)
df.shape
df.head()

,order_id,order_date,product_id,product_category,price,discount_percent,quantity_sold,customer_region,payment_method,rating,review_count,discounted_price,total_revenue
0,1,2022-04-13,2637,Books,128.75,10,4,North America,UPI,3.5,443,115.88,463.52
1,2,2023-03-12,2300,Fashion,302.60,20,5,Asia,Credit Card,3.7,475,242.08,1210.40
2,3,2022-09-28,3670,Sports,495.80,20,2,Europe,UPI,4.4,183,396.64,793.28
3,4,2022-04-17,2522,Books,371.95,15,4,Middle East,UPI,5.0,212,316.16,1264.64
4,5,2022-03-13,1717,Beauty,201.68,0,4,Middle East,UPI,4.6,308,201.68,806.72

In [5]:
# TODO: Clean up your Column Names (rename them to remove spaces if needed)
# Example: df = df.rename(columns={'Old Name': 'new_name'})
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ", "_")
)

In [ ]:
# TODO: Fix Date Columns (if applicable)
# Example: df['date_col'] = pd.to_datetime(df['date_col'])
df["order_date"] = pd.to_datetime(df["order_date"])

['order_id', 'order_date', 'product_id', 'product_category', 'price', 'discount_percent', 'quantity_sold', 'customer_region', 'payment_method', 'rating', 'review_count', 'discounted_price', 'total_revenue']

**Part 1 Analysis:**
*Double click here to edit.*
1. Does the row count match your expectation?
2. Did the column renaming work?
3. Have you changed any of the variable data types?

In [10]:
# TODO: Display the first 10-20 rows (head) and last 5 rows (tail) of your dataframe
df.head()
df.tail()

,order_id,order_date,product_id,product_category,price,discount_percent,quantity_sold,customer_region,payment_method,rating,review_count,discounted_price,total_revenue
49995,49996,2022-09-03,1433,Beauty,26.99,0,5,Middle East,Credit Card,2.4,386,26.99,134.95
49996,49997,2022-07-03,1428,Beauty,294.23,10,5,Asia,Credit Card,3.1,8,264.81,1324.05
49997,49998,2023-02-17,4651,Electronics,352.11,30,4,Asia,Debit Card,3.1,104,246.48,985.92
49998,49999,2022-09-30,4371,Beauty,307.54,5,1,Middle East,UPI,1.8,316,292.16,292.16
49999,50000,2023-06-29,2944,Home & Kitchen,253.44,30,1,Europe,Debit Card,2.1,464,177.41,177.41

**Visual Inspection:**
*Double click here to edit.*
1. Do the headers look correct?
2. Does the data at the bottom of the file look consistent with the top?

## Part 2: Deep Dive & Data Dictionary (2 Points)
You will now analyze the content of each column to build a "Data Dictionary" and assess data quality

In [11]:
# TODO: Use .describe(), .info(), or .unique() to analyze your columns
df.info()
df.describe(include="all")

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          50000 non-null  int64
 1   order_date        50000 non-null  datetime64[us]
 2   product_id        50000 non-null  int64
 3   product_category  50000 non-null  str
 4   price             50000 non-null  float64
 5   discount_percent  50000 non-null  int64
 6   quantity_sold     50000 non-null  int64
 7   customer_region   50000 non-null  str
 8   payment_method    50000 non-null  str
 9   rating            50000 non-null  float64
 10  review_count      50000 non-null  int64
 11  discounted_price  50000 non-null  float64
 12  total_revenue     50000 non-null  float64
dtypes: datetime64[us](1), float64(4), int64(5), str(3)
memory usage: 5.0 MB

,order_id,order_date,product_id,product_category,price,discount_percent,quantity_sold,customer_region,payment_method,rating,review_count,discounted_price,total_revenue
count,50000.000000,50000,50000.000000,50000,50000.000000,50000.000000,50000.000000,50000,50000,50000.000000,50000.000000,50000.000000,50000.000000
unique,NaN,NaN,NaN,6,NaN,NaN,NaN,4,5,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,Beauty,NaN,NaN,NaN,Asia,Wallet,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,8465,NaN,NaN,NaN,12526,10106,NaN,NaN,NaN,NaN
mean,25000.500000,2022-12-31 10:47:16.800000,2986.848740,NaN,252.507260,13.340700,2.999400,NaN,NaN,2.996316,249.329280,218.886566,657.331475
min,1.000000,2022-01-01 00:00:00,1000.000000,NaN,5.010000,0.000000,1.000000,NaN,NaN,1.000000,0.000000,3.530000,3.840000
25%,12500.750000,2022-07-02 00:00:00,1983.000000,NaN,127.840000,5.000000,2.000000,NaN,NaN,2.000000,125.000000,109.680000,240.320000
50%,25000.500000,2023-01-02 00:00:00,2983.000000,NaN,252.970000,10.000000,3.000000,NaN,NaN,3.000000,250.000000,215.805000,505.410000
75%,37500.250000,2023-07-02 00:00:00,3989.000000,NaN,376.335000,20.000000,4.000000,NaN,NaN,4.000000,374.000000,322.702500,968.970000
max,50000.000000,2023-12-31 00:00:00,4999.000000,NaN,499.990000,30.000000,5.000000,NaN,NaN,5.000000,499.000000,499.910000,2499.550000
std,14433.901067,NaN,1156.374535,NaN,143.025544,9.850694,1.415401,NaN,NaN,1.154295,144.251981,127.317681,526.223968

In [15]:
# TODO: Check for missing values in your columns
df["price"].unique()
df.isna().sum().sort_values(ascending=False)

order_id            0
order_date          0
product_id          0
product_category    0
price               0
discount_percent    0
quantity_sold       0
customer_region     0
payment_method      0
rating              0
review_count        0
discounted_price    0
total_revenue       0
dtype: int64

**Data Dictionary & Quality Check:**
*Double click here to edit. For your key columns, answer:*
1. **Column Name:** [Price]
   - **What it represents:** Price of the items
   - **Data Type Issue?:** No issue was found
   - **Sanity Check:** N/A
   - **Missing Data Plan:** N/A

## Part 3: Project Strategy (1.5 Points)
Now that you have critically assessed your data quality, you must map it to your research goals that you indicated in Project Assignment #1.

**Research Questions:** *Double click here to edit.*
1. Which product categories perform best? - Columns needed: product_category, total_revenue, quantity_sold
2. Are ratings and review counts linked to higher sales? - Columns needed: rating, review_count, total_revenue, quantity_sold

**Statistical Analysis Plan:** *Double click here to edit*

*Explain which statistical test (t-test, regression, etc.) you will use for each question and WHY.*
will use descriptive statistics and grouping in pandas by calculating total revenue and total quantity sold for each product category, then ranking categories and visualizing results with bar charts. This approach directly answers which categories perform best because it compares category-level totals.

I will test whether ratings and review counts are related to sales by calculating correlation between rating/review_count and both total_revenue and quantity_sold, and I may also run a simple linear regression to estimate how much sales change as ratings or review counts increase. Correlation and regression are appropriate because they measure and quantify relationships between numeric variables.

In [ ]:
# TODO: Create a new dataframe containing ONLY the columns you need for your research.
# project_df = df[['col1', 'col2', ...]]
project_df = df[[
    "product_category",
    "total_revenue",
    "quantity_sold",
    "rating",
    "review_count"
]].copy()

  product_category  total_revenue  quantity_sold  rating  review_count
0            Books         463.52              4     3.5           443
1          Fashion        1210.40              5     3.7           475
2           Sports         793.28              2     4.4           183
3            Books        1264.64              4     5.0           212
4           Beauty         806.72              4     4.6           308

In [17]:
# TODO: Display the head of your new "focused" dataframe to verify it looks correct.
project_df.head()

  product_category  total_revenue  quantity_sold  rating  review_count
0            Books         463.52              4     3.5           443
1          Fashion        1210.40              5     3.7           475
2           Sports         793.28              2     4.4           183
3            Books        1264.64              4     5.0           212
4           Beauty         806.72              4     4.6           308